tegehoge/LeacTion

- package.json
- src/components/CommentBlock.vue
- src/models/comment.ts
- src/models/event.ts
- src/models/talk.ts
- src/repository/firebase.ts
- src/repository/interface.d.ts
- src/repository/local_storage.ts
- yarn.lock
エミュレーターでの動作を確認したかったので実装しちゃいました。
#2 の内容です。
> Implement connection to firebase cloudfunctions.

- src/components/CommentInput.vue
- src/pages/Event.vue
https://github.com/tegehoge/LeacTion/issues/5
イベントページに、発表切り替えセレクトボックスを追加した
全体的にコードと仕様のレビューをお願いします🙇‍♀️
デザインは後からあてる前提で、超適当です・・・（我ながら分かりづらいと思っている）
> [add] Switching talk on event page

- src/App.vue
- src/components/CommentBlock.vue
- src/components/CommentInput.vue
- src/pages/Event.vue
`UserContext` を生成する場所を `App.vue` から `pages/Event.vue` に変更し、コメント入力やコメント表示の箇所で利用する
refs #1
> Create UserContext in Event page.

- src/App.vue
- src/components/AppHeader.vue
- src/components/CommentBlock.vue
- src/components/CommentInput.vue
- src/main.js
- src/pages/Event.vue
- src/pages/NewEvent.vue
- src/pages/Top.vue
> イベントページのデザイン変更

- src/components/EventInputForm.vue
- src/models/event.ts
- src/pages/Event.vue
- src/pages/EventEdit.vue
- src/router.js
- `/event/:eventId/edit` でイベント編集できるようにする
- パスワード確認モーダル（超シンプル）
- 既存の発表を消そうとしたときに警告を出す
~#15 に続き実装したものになります。 #15 を先にマージしてください。~
マージしました
> イベント編集画面の実装

- package.json
- src/components/AppHeader.vue
- src/components/EventHeader.vue
- src/components/Modal.vue
- src/main.js
- src/pages/Event.vue
- yarn.lock
- イベントページ右上のアイコンをハンバーガーメニューに変更
> イベントページのメニューを追加

- functions/src/index.ts
- src/components/CommentBlock.vue
- src/pages/Event.vue
- src/repository/local_storage.ts
#9 
- シークレットウィンドウなどの複数のブラウザで同一のイベントを開いたときに、コメントが同期されること
- #16 のマージ後、編集したイベントが同期されること
> 自動コメント取得・イベントデータ更新

- src/pages/Event.vue
> ブラウザのページが表示されていない状態では自動更新を行わない

- .github/workflows/check.yml
- .github/workflows/deploy.yml
- .gitignore
- CONTRIBUTING.md
- firestore.rules
- package.json
- src/client/firebase.ts
- src/components/CommentBlock.vue
- src/main.js
- src/models/event.ts
- src/pages/Event.vue
- src/repository/index.ts
- yarn.lock
> Firestoreのリアルタイムアップデート対応

- src/pages/EventEdit.vue
> イベント編集ページにヘッダを付ける

- .github/workflows/check.yml
- .github/workflows/deploy.yml
- package.json
- postcss.config.js
- tailwind.config.js
- vite.config.js
- vite.config.ts
- yarn.lock
> Upgrade to Tailwindcss 2

- package.json
- src/components/CommentBlock.vue
- src/components/CommentInput.vue
- tsconfig.json
- yarn.lock
> URL文字列にリンクを付ける

- src/components/AppHeader.vue
- src/main.js
> Add link to github

- src/repository/index.ts
https://github.com/tegehoge/LeacTion/pull/72#issuecomment-810672939
> PROD フラグを利用して開発用とを切り替える

- src/main.js
- src/pages/Event.vue
> 「未読コメント」ボタンの追加

- package.json
- src/components/EventInputForm.vue
- src/main.js
- tailwind.config.js
- yarn.lock
#66 
好みが分かれる部分かと思うが、ボタンで上下するより直感的でわかりやすいのではないか。
> 発表者の変更をdraggableにする

- package.json
- src/components/CommentBlock.vue
- src/components/CommentInput.vue
- src/components/EventInputForm.vue
- src/main.js
- src/pages/EventEdit.vue
- src/pages/NewEvent.vue
- yarn.lock
> sweetalert2 を使って確認や通知をリッチにする

- src/components/CommentBlock.vue
- src/components/CommentInput.vue
- src/index.css
- src/models/comment.spec.ts
- src/models/comment.ts
- tsconfig.json
コメント入力時の `<`, `>` のエスケープやHTML出力処理を `Comment` クラスのロジックとしてまとめ、テストを行うようにした。
> Move sanitizing and HTML output into Comment class.

- src/pages/Event.vue
スクロールが最下部にあるときは最新コメントを追従して表示する
#90
> 最新コメントを追従する

- src/components/AppHeader.vue
- src/pages/NotFound.vue
- src/router.js
> Add NotFound page.

- firebase.json
- functions/package-lock.json
- functions/package.json
- functions/src/index.ts
- functions/src/types.d.ts
- package.json
- src/components/CommentBlock.vue
- src/components/EventInputForm.vue
- src/models/event.spec.ts
- src/models/event.ts
- src/pages/Event.vue
- src/pages/EventEdit.vue
- src/repository/firebase.ts
- src/repository/index.ts
- src/repository/interface.d.ts
- src/repository/local_storage.ts
- storage.rules
- yarn.lock
> アーカイブ機能の実装

- .github/workflows/deploy.yml
> Use workload identity for deployment.

- index.html
> Google Analytics タグの追加

- index.html
- public/robots.txt
> robots.txtの追加
